### ISSUE TITLE
Check LFUCG license compatibility with OSM

### ISSUE THREAD

**Issue by maptastik** [openlexington/building-import#1]
Per  the [import guidelines](http://wiki.openstreetmap.org/wiki/Import/Guidelines), imported data need to have a license compatible with OSM's ODbL license.

LFUCG's data is licensed under [ODC PDDL](http://opendefinition.org/licenses/odc-pddl/) which I assume should work it would behoove us to double check.

**Comment by maptastik** [comment]
["Terms of Use for data.lexingtonky.gov"](http://data.lexingtonky.gov/terms)

Not sure if this changes anything

**Comment by chaserx** [comment]
see license compatibility. https://wiki.openstreetmap.org/wiki/Import/ODbL_Compatibility

I think we're good, also I'm a hacker not a lawyer.
